export const ERROR_CODES = {
  LLM_GENERATION_FAILED: 'LLM_GENERATION_FAILED',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  PROJECT_ERROR: 'PROJECT_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REGISTRY_ERROR: 'REGISTRY_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
